### ISSUE TITLE
Invert Issue (Suggested fix included)

### ISSUE THREAD

**Issue by Sayayaya** [heisarzola/multi-channel-image#2] opened 2022-06-16 16:46 UTC
Firstly, thank you for adding the Invert feature!

I noticed that fully black pixel values (0) were not getting inverted. I managed to fix it myself, here's the change:-

ImageUtility.cs Line 115

`if (intensity > 0 & intensity <= 255)
    {
        if (invert) { intensity = 255 - intensity; }`

The invert logic is only applied if greater than 0, because the corresponding else to this if does not invert

I fixed the invert by changing greater-than (>) to greater-than-or-equals (>=) ie if (intensity >= 0...

**Comment by heisarzola** [comment] 2022-06-16 16:47
I'll patch it in on the afternoon.
(Well, my afternoon, which should be like 10 hours away.)

**Comment by heisarzola** [comment] 2022-06-17 00:11
Just wanted to let you know that while adding that fix is pretty much immediate, I'm going to also try to cram in this new image generation algorithm while I'm at it, which is presumably hundreds of times faster than what there is currently in place. Adding this second bit is likely going to be the bit that takes a while.

**Comment by heisarzola** [comment] 2022-06-17 04:12
The new version with this fix has been uploaded, you can find it at:
https://github.com/heisarzola/multi-channel-image/releases/tag/V.1.2.0 

Thanks to (41e80a0314d1fe42caf235ebc00b8b968aefef55) the image generation and extraction should also be sped up dramatically compared to before.

In case I totally missed the mark and the issue is still there, feel free to reopen this.

**Closed as completed by heisarzola** 2022-06-17 04:12 UTC
